trigger:
  branches:
    include:
      - main
      - stage
      - devel

pool:
  name: Default

variables:
  - name: REGION
    value: 'us-west-1'
  - name: DISTRIBUTION_ID
    value: 'E9LOQQH9RY8JT'
  - name: bucketname
    value: 'fullstack-webapp-production'  

stages:
  - stage: Develop
    displayName: 'CI/CD to development environment'
    jobs: 
      - job: DevelopCI
        displayName: 'DevelopCI'
        condition: |
          eq(variables['build.sourceBranch'], 'refs/heads/develop')
        steps: 
          - template: ADO/CI.yml
      - job: DevelopCD
        displayName: 'DevelopCD'
        dependsOn: DevelopCI
        condition: |
          and (succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/develop'))
        steps: 
          - template: ADO/CD.yml

  - stage: Stage
    displayName: 'CI/CD to stage environment'
    jobs: 
      - job: StageCI
        displayName: 'StageCI'
        condition: |
          eq(variables['build.sourceBranch'], 'refs/heads/stage')
        steps: 
          - template: ADO/CI.yml
      - job: StageCD
        displayName: 'StageCD'
        dependsOn: StageCI
        condition: |
          and (succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/stage'))
        steps: 
          - template: ADO/CD.yml

  - stage: Production
    displayName: 'CI/CD to production environment'
    jobs: 
      - job: ProductionCI
        displayName: 'ProductionCI'
        condition: |
          eq(variables['build.sourceBranch'], 'refs/heads/main')
        steps: 
          - template: ADO/CI.yml
      - job: ProductionCD
        displayName: 'ProductionCD'
        dependsOn: ProductionCI
        condition: |
          and (succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/main'))
        steps: 
          - template: ADO/CD.yml